### ISSUE TITLE
Are all  the channels real-value?

### ISSUE THREAD

**Issue by xiashh** [yihanjiang/turboae#1]
I check the source code and the paper, and I find that the channels are all assumed as real-value. So I wonder if I try to use the complex channels which is practical actually, does it work?

**Comment by yihanjiang** [comment]
The code also supports BSC and BEC, but TurboAE has not superb performance on discrete channels. 

The complex channel will work, as you can just use the real and image parts as two separated continuous channels. I haven't tried, but it should work.

**Comment by xiashh** [comment]
Thank you for your response.

发自我的iPhone

在 2019年11月3日，上午6:00，Yihan Jiang <notifications@github.com> 写道：

﻿

The code also supports BSC and BEC, but TurboAE has not superb performance on discrete channels.

The complex channel will work, as you can just use the real and image parts as two separated continuous channels. I haven't tried, but it should work.

**Comment by yihanjiang** [comment]
Working on improving discrete channels.
