### ISSUE TITLE
Baseline Implementation

### ISSUE THREAD

**Issue by aprilbian** [yihanjiang/turboae#2]
Hi Yihan, could you please tell me if your implementation for the ldpc/polar/turbo shown in the Figure 1 are using the code from the "commpy" folder on your github?

Thanks in advance!

**Comment by yihanjiang** [comment]
Sorry, I lost my edu account with some unknown reason.  The Turbo benchmark are from commpy folder (you can use Turbo-757/LTE). LDPC/Polar are done via Vienna 5G simulator (https://www.nt.tuwien.ac.at/research/mobile-communications/vccs/vienna-5g-simulators/), which requires you to ask them for the code.
